<a href="https://colab.research.google.com/github/ridaSE2016/NumpyAssignment/blob/main/Numpy_Assignment1_PIAIC_Batch35_Q2RIDAHAMID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.empty((10))

array([3.24561446e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

3. Create a vector with values ranging from 10 to 49

In [4]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [6]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [7]:
np.__version__

'1.19.4'

7. Print the dimension of the array in question 3


In [8]:
x.ndim

1

8. Create a boolean array with all the True values

In [9]:
boole1 = np.array([[2,0], [2,1]])
boole2 = np.array([[6,4], [5,8]])
boole1 < boole2


array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [10]:
a = np.array([[1,2],[2,1]])
a

array([[1, 2],
       [2, 1]])

10. Create a three dimensional array



In [11]:
arr = np.array([[1,2,3],[3,4,5],[6,7,8]])
arr


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
y  = np.arange(5,20)
y = y[::-1]
y


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
a = np.empty(10)
a[4] = 1
a

array([3.24561446e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

13. Create a 3x3 identity matrix

In [14]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr.astype('float')

array([[1., 2., 3.],
       [3., 4., 5.],
       [6., 7., 8.]])

15. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
    arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [18]:
arr = np.array([0,1,2,3,4,5,6,7,9])
arr[arr % 2 != 0 ]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [19]:
y = arr[arr % 2 != 0 ] 
y = arr
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 9])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
arr[5:9] = 12
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr1 = np.ones((5,5))
arr1[1:-1, 1:-1] = 0
arr1


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
arr2d = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
arr2d[0]

array([0, 1])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
arr2d = np.array([[[[0,1,2],[3,4,5]],[[7,8,9],[10,11,12]]]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
arr2d = np.array([[0,1,2],[3,4,5],[7,8,9],[10,11,12]])
arr2d[0:2,2]




array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
x= np.random.random((10,10))
xmax= x.max()
xmin =x.min()
xmax, xmin

(0.998628479438946, 0.006546678056187694)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [35]:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(b)
print(a)
print(np.intersect1d(a,b))

[ 7  2 10  2  7  4  9  4  9  8]
[1 2 3 2 3 4 3 4 5 6]
[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [42]:
print(a)
print(b)
c = np.where(np.in1d(a,b))[0]
print(c)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
data[names != 'Will']


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.04908083  0.78183142 -0.75572023  0.66569056]
 [-1.85326998  1.7500788  -0.45783033  0.92793107]
 [ 1.65664618 -0.5741043   0.31023469 -0.95183439]
 [-1.09675659  0.42507074  0.35625789 -1.15731386]
 [-1.02290318  0.06761483  0.48314577 -0.03917509]
 [ 0.5778025   0.55097818 -0.91857673  2.39015585]
 [ 1.28443753 -1.7801923  -1.85046667  0.12710045]]


array([[-1.04908083,  0.78183142, -0.75572023,  0.66569056],
       [-1.85326998,  1.7500788 , -0.45783033,  0.92793107],
       [-1.09675659,  0.42507074,  0.35625789, -1.15731386],
       [ 0.5778025 ,  0.55097818, -0.91857673,  2.39015585],
       [ 1.28443753, -1.7801923 , -1.85046667,  0.12710045]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[(names!="Will") & (names != "Joe")]


array([[-0.37944502,  1.41714808,  1.17321386, -0.87537325],
       [-0.39263986,  0.24108557,  1.48323383, -0.12175332]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [79]:

rand_arr = np.random.uniform(1,15, size=(5,3))
rand_arr

array([[ 3.73935188,  3.24075625,  4.21044299],
       [ 2.36801855,  1.18558516, 12.62080226],
       [13.33979868,  6.92697625,  7.83723985],
       [10.52072707,  2.43433709, 13.422266  ],
       [ 1.36057679,  7.43016987,  6.13509692]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [81]:
arr = np.random.uniform(1,16,size =(2,2,4))
arr

array([[[ 8.65989336, 12.53520295,  2.86808004,  2.99739738],
        [14.20885493, 14.84080975,  3.30448807,  7.34455818]],

       [[14.80058398,  6.41909028, 15.08423493,  9.82494492],
        [10.34386657,  3.05633687, 15.67123429,  8.43058164]]])

33. Swap axes of the array you created in Question 32

In [82]:
arr.swapaxes(1,2)

array([[[ 8.65989336, 14.20885493],
        [12.53520295, 14.84080975],
        [ 2.86808004,  3.30448807],
        [ 2.99739738,  7.34455818]],

       [[14.80058398, 10.34386657],
        [ 6.41909028,  3.05633687],
        [15.08423493, 15.67123429],
        [ 9.82494492,  8.43058164]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [117]:
arr = np.arange(10)
x = np.sqrt(arr)
print(x) 
x[x < 0.5]= 0
x






[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [157]:
x = np.random.randn(12) 
print(x)
y = np.random.randn(12)
print(y)
np.maximum(x,y)


[ 0.57776761  0.56796257  0.25547748  0.88434406  0.59070204  0.46113325
 -0.05115014  0.86939275 -0.01629528  1.83540147  1.66641381  0.68899193]
[ 0.10084454  0.17026235 -0.3880032   0.87418988  0.63442825 -0.38895811
  0.56969528  0.88196207  1.33622784  1.42505113  0.97786856  1.23949988]


array([0.57776761, 0.56796257, 0.25547748, 0.88434406, 0.63442825,
       0.46113325, 0.56969528, 0.88196207, 1.33622784, 1.83540147,
       1.66641381, 1.23949988])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [186]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
common = np.unique(names)
common
updated = np.sort(common)
updated

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [163]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b)
print(result)


[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [180]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
C = np.delete(sampleArray, 1, 1)
newColumn = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
sampleArray

array([[34, 10, 43, 73],
       [82, 10, 22, 12],
       [53, 10, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [182]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [191]:
a = np.arange(20)
print(a)
a = np.cumsum(a)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
